// ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
// Source : scripts/extract-ui-strings.mjs (node scripts/extract-ui-strings.mjs)
//
// Catalogue de toutes les chaînes UI françaises du panel, extraites
// statiquement (texte JSX, props de texte, toasts). Utilisé par l'action admin
// « Pré-traduire tout » pour remplir le cache des 7 langues en une fois, sans
// avoir à naviguer manuellement dans chaque page.
//
// 1451 chaînes.

export const PANEL_STRINGS: readonly string[] = [
  "— Camille L., cheffe & propriétaire",
  ", et les",
  ", tu vas recevoir un email avec un lien pour réinitialiser ton mot de passe. Il est valable",
  ", utilise le portail Stripe ci-dessus.",
  ": si une photo passe mal (reflet, écriture manuscrite), bascule sur « Coller le texte » — c'est le plus fiable.",
  ": ton QR pointe toujours vers ta carte à jour, change ta carte 50 fois sans ré-imprimer",
  "· ⚠ Trop faible (auto-correction au rendu pour rester lisible)",
  "» ne sera pas envoyé à l'heure prévue. Tu pourras le re-programmer si tu changes d'avis.",
  "(150×150px)",
  "(customer Stripe inconnu)",
  "(encore",
  "(id=",
  "(obligation comptable 10 ans)",
  "(offert)",
  "(ratio 16/9)",
  "(verrouillé)",
  ") seront aussi supprimés. Action irréversible.",
  "% écoulé",
  "% taux d'activation",
  "← Précédent",
  "→ Demander un nouveau lien",
  "↳ Sous-catégorie de",
  "× article",
  "⌘B",
  "⌘K",
  "●●● 5G ▮",
  "☀️ Carte du midi (11h30-15h)",
  "☀️ Service du midi",
  "⚠️ Attention :",
  "⚠️ Paiement en retard",
  "⚠️ Supprime toutes tes catégories + produits actuels avant l'import. Sinon, l'import s'ajoute après.",
  "🇫🇷 Made in France",
  "✅ Paiement confirmé. La mise à jour est en cours via Stripe recharge la page dans quelques secondes si le statut n'a pas encore changé.",
  "✓ Définie",
  "✓ Les 6 colonnes existent en DB",
  "✓ Payée",
  "✗ Absente ajoute-la dans Railway Variables avant de tester",
  "❌ Erreur SELECT information_schema :",
  "⭐ Relance 24h après la roulette",
  "🌙 Carte du soir (18h30-23h)",
  "🌙 Service du soir",
  "🍹 Happy Hour",
  "🍹 Happy Hour (18h-19h)",
  "🎁 Essai",
  "🎁 Label du lot (avec emoji)",
  "🎂 Anniversaire du client",
  "🎉 1 an après le 1er contact",
  "🎯 Personnalisé",
  "🏠 Catégorie principale (top-level)",
  "💡 Livraison offerte à partir de",
  "💬 Réponse suggérée par l'IA",
  "📅 Prévu le",
  "🔒 Paiement sécurisé Stripe CB / SEPA / Apple Pay",
  "🚫 Service suspendu : paiement échoué",
  "€ / SMS",
  "€ par SMS",
  "0 = pas de seuil",
  "06 12 34 56 78 (ou +33 6 12 34 56 78)",
  "1 heure",
  "1. Colonnes horaires en DB",
  "1. Confirme ton email :",
  "1. Import prospects",
  "1. Photo du menu",
  "1. Texte du menu",
  "10 contacts les plus récents avec téléphone.",
  "10 dernières campagnes envoyées.",
  "10 plus récents",
  "10 plus scannés",
  "100 sets de table avec ton QR code unique. Format A4, pelliculage mat.",
  "12 rue de la Paix",
  "14 jours d'essai Pro offerts, aucune carte bancaire requise.",
  "2. Options d'import",
  "2. Tape",
  "2. Valeurs actuelles (lecture Prisma)",
  "2. Variants emails",
  "3. Pipeline enrichissement",
  "3. Test de sauvegarde directe (raw SQL)",
  "30 secondes",
  "4. Export Smartlead",
  "50 derniers événements",
  "50 derniers scans refresh auto toutes les 30s",
  "6 plats",
  "7j/7",
  "8 caractères minimum",
  "À facturer",
  "à imprimer",
  "À noter :",
  "À propos",
  "À qui envoyer",
  "a toujours accès à tout (non éditable). Les modifications s'appliquent immédiatement au gating.",
  "À utiliser uniquement sur demande RGPD du client ou compte abandonné depuis 6+ mois.",
  "A/B test des sujets et corps de mails. Le bandit Thompson Sampling favorise progressivement les meilleurs.",
  "Abonnement annulé.",
  "abonnement Stripe",
  "Accent / CTA",
  "Accepte les SMS marketing",
  "Achats SMS",
  "Acheter à nouveau",
  "Acheter un pack de SMS",
  "Acquisition & Enrichissement",
  "Actif",
  "Actifs",
  "Action",
  "Action irréversible.",
  "Action irréversible. Les traductions cachées seront aussi effacées.",
  "Action irréversible. Si des commandes existent pour ce produit, la suppression sera refusée archive-le à la place.",
  "Actions",
  "Actions rapides",
  "Activation de votre carte",
  "Active",
  "Active le site pour voir la preview live.",
  "Activer",
  "Activer la démo immédiatement",
  "Activer les frais de port",
  "Activité 30 jours",
  "Activité du SaaS",
  "actuel",
  "Actuel",
  "Admin",
  "Adresse",
  "Adresse email du destinataire",
  "Affichage limité aux 1000 participations les plus récentes. Utilise l'export CSV pour avoir la liste complète.",
  "Affiché à côté du nom de la catégorie sur la carte publique. Clic pour parcourir tous les emojis.",
  "Affiché en haut de la modale roulette sur la carte publique.",
  "Affiche un message ponctuel à tes clients : nouvelle carte, brunch du dimanche, soirée DJ…",
  "Affiche un message ponctuel sur la carte : nouvelle offre, événement, soirée DJ. Une pop-up bien placée, ça vend.",
  "Affiche une carte Google Maps cliquable dans le pied de page de ta carte digitale, avec un bouton « itinéraire ».",
  "Affichée si un produit n'a pas la sienne.",
  "Afficher la carte Maps",
  "Afficher sur la carte publique",
  "Affichés en footer de la carte publique. Le lien Google Review alimente le jeu roulette.",
  "Affluence horaire",
  "AI :",
  "Aide Claude à lire correctement les caractères spéciaux.",
  "Ajouté",
  "Ajoute des clients ici",
  "Ajouter",
  "Ajouter au panier (",
  "ajouter des plats, puis reviens choisir ta vitrine.",
  "Ajouter ton premier client",
  "Ajouter un client",
  "Ajouter un lot",
  "Ajouter un palier",
  "Ajouter un restaurant",
  "Ajouter une photo",
  "Ajouter une taille",
  "Ajuste le dernier lot pour atteindre 100%",
  "allergène",
  "Allergènes",
  "Analyse",
  "Analyse du menu en cours… (5-30 secondes)",
  "Analyser (dry-run)",
  "Année d'ouverture",
  "Anniversaire (optionnel, pour l'automatisation)",
  "Annonces in-carte",
  "Annule les souscriptions Stripe actives",
  "Annulée",
  "Annulées",
  "Annuler",
  "Annuler cette campagne programmée ?",
  "Annuler la campagne",
  "Annuler la programmation",
  "Anonymise les données personnelles (email, nom, téléphone, adresse)",
  "Aperçu",
  "Aperçu (valeurs d'exemple : Marc / Dupont / Le Tire-Bouchon)",
  "Aperçu bouton",
  "Aperçu de la carte publique",
  "Aperçu live",
  "Aperçu mobile",
  "Apparaît dans le récap panier et sur la facture.",
  "Appareil",
  "Appareils",
  "Appliquer",
  "Archivé",
  "Archivé invisible mais conservé",
  "Archive les restaurants et empêche tout login",
  "Archiver",
  "Archiver ce compte ?",
  "Archiver le compte",
  "ARR projeté",
  "article",
  "Articles",
  "Au verre 12cl : 14€",
  "Aucun",
  "Aucun achat de SMS pour ce client.",
  "Aucun achat de SMS pour l'instant",
  "Aucun autre produit à proposer. Crée d'autres plats pour les marier ensemble.",
  "Aucun bon de commande en cours toutes les commandes sont livrées ou annulées.",
  "Aucun bon de commande pour ce client.",
  "Aucun client ajouté manuellement pour l'instant.",
  "Aucun client trouvé.",
  "Aucun contact pour l'instant. Active la roulette d'avis pour en collecter.",
  "Aucun destinataire trouvé avec ce filtre. Vérifie que tes clients ont bien laissé leur téléphone via la roulette.",
  "Aucun emoji ne correspond",
  "Aucun jeu configuré",
  "Aucun jeu configuré.",
  "Aucun log enregistré pour le moment.",
  "Aucun log enregistré.",
  "Aucun membre. Invite quelqu'un ci-dessus pour commencer.",
  "Aucun palier c'est le tarif forfaitaire au-dessus qui sera appliqué à toute commande.",
  "Aucun pop-up. Crée le premier pour annoncer un événement.",
  "Aucun produit dans cette catégorie.",
  "Aucun prospect en attente. Lance d'abord l'import.",
  "Aucun prospect ne correspond à ces filtres.",
  "Aucun QR code actif à imprimer.",
  "Aucun QR code dans ce filtre.",
  "Aucun restaurant en DB.",
  "Aucun restaurant.",
  "Aucun résultat pour",
  "Aucun scan attribué à un QR code (les visiteurs sont arrivés via URL directe).",
  "Aucun scan localisé sur la période.",
  "Aucun scan sur la période.",
  "Aucun sélectionné = tous les jours.",
  "Aucun témoignage. Copie-colle des avis Google ou TripAdvisor.",
  "Aucun variant pour cette campagne.",
  "Aucune activité récente.",
  "Aucune automatisation pour l'instant. Crée la première ci-dessous : envoi automatique pour les anniversaires de tes clients, par exemple.",
  "Aucune campagne envoyée pour l'instant.",
  "Aucune catégorie",
  "Aucune commande ne matche les filtres.",
  "Aucune commande pour l'instant",
  "Aucune donnée pour cette période.",
  "Aucune facture d'abonnement",
  "Aucune facture d'abonnement.",
  "Aucune participation",
  "Aucune photo. Le pattern bento s'active à partir de 6 photos (idéalement 8).",
  "Aucune réponse reçue pour cette campagne pour l'instant.",
  "Aucune session active.",
  "Audit trail",
  "Audit trail centralisé : actions admin (création client, changement de plan, impersonation), actions critiques système. Cap à 200 derniers événements.",
  "Audit trail complet pour ce compte.",
  "Auteur (ex: Marie D. · Le Fooding)",
  "Auto",
  "Auto-généré (16 caractères). Tu copies-colles ce mot de passe pour le client, il pourra le changer dès sa première connexion.",
  "Auto-généré depuis le nom si vide.",
  "automatiquement via la roulette d'avis. Tu peux aussi en ajouter manuellement (anciens clients, contacts du carnet…) avec le bouton « Ajouter un client ».",
  "Automatisation créée",
  "Automatisation supprimée",
  "Automatisations",
  "autre",
  "autres",
  "Autres campagnes",
  "Avec téléphone",
  "avec ton logo et tes couleurs (configurés dans Mon resto)",
  "Backoffice",
  "Badge (optionnel)",
  "Bandeau Réservation",
  "Banner (image plein écran)",
  "Bannière",
  "Bascule manuelle des plans bypasse Stripe. À utiliser pour offrir un upgrade gratuit, débloquer une démo, ou corriger un sub Stripe désynchronisé.",
  "Base clients",
  "BC / Factures",
  "BC / Factures (",
  "BC / Factures du client",
  "BC 24h",
  "BC en cours",
  "BC-",
  "BIC :",
  "Bienvenue sur Ruliz 🎉",
  "Bistronomie sud-ouest dans une cave voûtée du XVIIIe.",
  "Bistronomie, bar à vins, signature",
  "Bistrot bordelais depuis 1987",
  "Bistrot mar-sam",
  "Bistrot moderne, produits du marché, vins vivants.",
  "bon",
  "Bons de commande boutique",
  "Bonus",
  "Bordeaux",
  "Bounce / Spam",
  "Boutique",
  "Boutique QR",
  "Brasserie, café, vegan, healthy",
  "Breakup poli",
  "Brouillon",
  "Brouillon invisible aux clients",
  "Business",
  "Bypass Stripe loggé dans /admin/logs",
  "C'est la cause du bug. Click le bouton ci-dessous pour les créer.",
  "CA boutique",
  "CA encaissé",
  "CA généré (estimation)",
  "Cadeau révoqué retour en freemium",
  "Campagne outreach",
  "Campagne programmée annulée",
  "Capacité totale en unités. Laisse vide pour stock illimité.",
  "Capital",
  "caractères",
  "caractères. Inutile de mettre en forme : colle tel quel, Claude s'occupe de la structure.",
  "Caractéristiques (bullet list)",
  "Carrousel horizontal",
  "Carte Google Maps",
  "Carte pré-générée — modifiable juste après activation.",
  "Carte prête",
  "Carte Ruliz",
  "cat.",
  "Catalogue",
  "Catalogue produits",
  "catégorie",
  "Catégorie",
  "Catégorie parente (optionnel)",
  "Catégorie principale",
  "Catégorie principale (top-level)",
  "Catégorie supprimée",
  "catégories",
  "Catégories",
  "Catégories Produits",
  "Ce bon de commande n'est pas contractuel. Une facture définitive sera émise après réception du paiement.",
  "Ce bouton fait un UPDATE raw SQL direct sur le restaurant",
  "Ce client n'a pas encore de restaurant.",
  "Ce client n'a pas encore de restaurant. Crée-lui-en un ci-dessus pour qu'il puisse accéder à son panel.",
  "Ce lien n'est plus valable",
  "Ce mois",
  "Ce nom apparaîtra sur le téléphone de tes clients à la place de ton numéro. 11 caractères max, lettres et chiffres uniquement (pas d'espace ni d'accent). Ton choix est mémorisé pour la prochaine fois.",
  "Ce produit n'est plus disponible. Reviens plus tard ou contacte le support si urgent.",
  "Ce que tu reçois",
  "Ces infos apparaissent sur la carte publique scannée par tes clients.",
  "Cette action supprimera",
  "Cette fonctionnalité demande",
  "Cette fonctionnalité n'est disponible sur aucun plan pour le moment.",
  "CGV",
  "Changer le plan",
  "Changer mon mot de passe",
  "Chaque restaurant a sa propre carte, ses QR codes et ses stats. Tu pourras basculer entre eux depuis ce menu.",
  "Chargement…",
  "Charger",
  "Choisir la photo ou le PDF du menu",
  "Choisir un logo",
  "Choisir une bannière",
  "Choisis 1 à 4 produits à mettre en vitrine sur ton site. L'ordre de sélection = ordre d'affichage. Vide = top-4 automatique par position.",
  "Choisis quand le SMS part automatiquement.",
  "Choisis un nouveau mot de passe",
  "Choisis un plan ci-dessous pour la débloquer.",
  "Choisis une photo/PDF de ton menu, ou colle directement son texte.",
  "Citation",
  "Clair",
  "Classic (EB Garamond)",
  "Classification reply via Anthropic Haiku → template approprié → délai humain 2-30 min → envoi",
  "Claude analyse et extrait : catégories, produits, descriptions, prix, allergènes.",
  "Cleanup R2 images orphelines",
  "Clic pour insérer un tag personnalisé :",
  "Clic pour le graphique →",
  "Clic sur un jour pour l'activer/désactiver.",
  "Click",
  "Click pour choisir parmi 250+ emojis classés",
  "Click preview",
  "Click rate",
  "clics",
  "Clics produits",
  "client",
  "Client",
  "Client créé.",
  "Client supprimé",
  "Clients",
  "Clients ajoutés manuellement (sélection)",
  "Cliqué",
  "Clique sur « Nouveau produit » pour commencer.",
  "Code postal",
  "Coller le texte",
  "Coller une URL",
  "Collez l'URL ex :",
  "colonnes manquantes",
  "commande",
  "Commande annulée",
  "Commande annulée paiement indisponible",
  "Commande créée mais ID introuvable",
  "Commande tes supports physiques",
  "Commande tes supports QR",
  "Commandes",
  "Commandes boutique",
  "Comment ça marche",
  "Comparaison période actuelle vs précédente.",
  "Compléter à 100%",
  "Comptabilité",
  "Comptabilité admin",
  "Compte",
  "Compte restaurateur. Tu peux activer la démo immédiatement, et il configurera son premier restaurant après sa première connexion.",
  "Concise, appétissante. La traduction automatique conservera ton ton.",
  "Confidentialité",
  "Config actuelle",
  "Configuration",
  "Confirme ton mot de passe",
  "Connecté",
  "Connecté. Redirection vers le tableau de bord…",
  "Connexion…",
  "Connexions",
  "Conseillé : 3 à 10s. Trop court = intrusif, trop long = le client est déjà parti scroller la carte.",
  "Conserve les",
  "Console admin",
  "Construis ta carte",
  "Contact",
  "contact@…",
  "contacts clients SMS",
  "contacts récupérés",
  "Contacts SMS",
  "Continuer avec Google",
  "Continuer le tour",
  "Contraste :",
  "Conversion → Client Pro",
  "Conversions",
  "Convert",
  "Converti",
  "Coordonnées",
  "Coordonnées de connexion. Pour changer ton email, contacte le support à",
  "Coordonnées du restaurateur. L'email est immuable.",
  "Copié",
  "Copie-colle le contenu de ton menu (depuis ton site web, un PDF, un Word…). C'est la méthode la plus fiable : Claude structure le texte en catégories, produits et prix.",
  "Copier sur la semaine",
  "Côté carte publique, les clients verront « dès",
  "Couleur d'accent (vide = couleur du resto)",
  "Couleur de la catégorie (optionnel)",
  "Couleur fond des boutons",
  "Couleur texte des boutons",
  "Couleurs",
  "Couleurs de la carte publique",
  "Coût estimé",
  "CP",
  "Création réussie mais ID manquant. Recharge la page.",
  "Création…",
  "Crédit SMS",
  "Crédit SMS disponible",
  "Créé",
  "Crée d'abord un jeu pour pouvoir voir les participants.",
  "Crée la première pour structurer ta carte.",
  "Créé le",
  "Crée ta première catégorie (Entrées, Plats, Boissons…) pour commencer à ajouter tes produits.",
  "Crée ton compte gratuit",
  "Crée ton premier restaurant pour démarrer. Tu pourras affiner les détails (logo, couleurs, réseaux sociaux) juste après.",
  "Créer",
  "Créer l'automatisation",
  "Créer le compte",
  "Créer le restaurant",
  "Créer mon compte",
  "Créer mon premier produit",
  "Créer mon restaurant",
  "Créer un client",
  "Créer un compte →",
  "Créer un pop-up",
  "Créer un restaurant",
  "Créer une automatisation",
  "Créer une catégorie",
  "Créneau d'affichage",
  "Créneau d'affichage du produit",
  "CSV : email, nom, ville, code_postal, adresse, telephone, site_web, logo_url, photo_cover, rating, nb_reviews, niveau_prix.",
  "CSV prêt à uploader : email, nom, ville, first_name, preview_url.",
  "CSV Smartlead (",
  "Cycle :",
  "dans l'env pour activer les paiements.",
  "dans ta carte",
  "dans ton équipe. Tu n'es pas listé : tu es propriétaire.",
  "Dark",
  "Date",
  "Date d'inscription (récent)",
  "Date de début",
  "Date de fin",
  "Date et heure d'envoi",
  "de commande non livré",
  "de produits (purgés du stockage)",
  "Debug horaires de service",
  "Début",
  "Déclencheur",
  "Décoche pour masquer (brouillon).",
  "Décoche pour mettre en pause sans supprimer la config.",
  "Définis ce à quoi chaque plan donne accès. Le plan",
  "Définis tes paliers par tranche de poids. Le tarif appliqué à chaque commande est calculé à partir du",
  "Définit les horaires utilisés pour les créneaux d'affichage des catégories (carte midi, carte soir, happy hour). Tu peux ensuite cocher l'un de ces créneaux dans l'éditeur de menu pour qu'une catégorie n'apparaisse que pendant ces horaires.",
  "définitivement",
  "déjà commandée",
  "Déjà un compte ?",
  "Déjeuner",
  "Délai avant l'auto-popup (secondes)",
  "Demander un avis Google avant de jouer",
  "Démo",
  "Démo active",
  "Démo terminée",
  "depuis le lancement",
  "Depuis mon ordi",
  "Dernière connexion",
  "Dernières 24h",
  "Dernières commandes BC",
  "Dernières roulettes",
  "Derniers contacts collectés",
  "Derniers gagnants",
  "Derniers signups",
  "des produits du panier (somme des grammages × quantités). Le montant est snapshoté sur la commande au moment de la création.",
  "Dès que tes premiers clients tourneront la roue depuis la carte publique, ils apparaîtront ici avec leurs coordonnées.",
  "Désactive pour inverser (texte gauche, photo droite).",
  "désactivée",
  "Désactiver",
  "Description",
  "Description (optionnel)",
  "Description du prix (optionnel)",
  "Destinataires",
  "Détail",
  "Détecte automatiquement la langue de ta carte",
  "Détermine quand tes créneaux (carte midi, happy hour, carte soir, personnalisé) sont actifs. Important si tu as des clients hors fuseau France métropolitaine.",
  "Deux paliers ont la même limite de poids.",
  "Devise",
  "Devise par défaut",
  "Diagnostic complet pour comprendre pourquoi les heures Happy Hour ne se sauvegardent pas.",
  "Didacticiel",
  "Didacticiel réactivé la bulle va réapparaître 👋",
  "Dîner",
  "dinnerEnd :",
  "dinnerStart :",
  "Disposition réinitialisée",
  "Distribué",
  "Distribuer",
  "Doc ↗",
  "Donne le même % à tous les lots",
  "Donne un nom à ton restaurant.",
  "Donne un nom au restaurant.",
  "Données à jour",
  "dont la limite ≥ poids total panier. Si poids dépasse tout, on prend le dernier (le plus lourd).",
  "Droits & Plans",
  "Du CSV brut à la carte digitale personnalisée",
  "Dupont",
  "Durée (jours)",
  "Échéance",
  "Échec",
  "échecs",
  "Échecs",
  "Écrase tout. Utile après changement de la langue native.",
  "Écrase toutes les traductions existantes. Utile après un changement de données ou de schéma.",
  "Édite ta carte",
  "Éditer",
  "Éditer la catégorie",
  "Editer les 16 variants",
  "Éditeur",
  "Éditeur de carte",
  "Édition",
  "Editorial (Instrument Serif italic)",
  "Effacer",
  "Effacer les filtres",
  "Effectivement supprimés",
  "Élégant, gastronomique",
  "Email",
  "Email (optionnel)",
  "Email bienvenue",
  "Email contact",
  "Email de contact",
  "Email du compte",
  "Email envoyé !",
  "Email ou nom…",
  "Email professionnel",
  "Email, nom ou numéro de facture…",
  "Email, nom, restaurant…",
  "Email, prénom, nom du client…",
  "Émis le",
  "Emoji :",
  "Emoji (optionnel)",
  "en attente",
  "En attente",
  "en attente)",
  "En cours…",
  "En créant un compte, tu acceptes nos",
  "En France",
  "en majuscules",
  "En préparation",
  "en retard",
  "en stock",
  "Enregistrer",
  "Enregistrer les plans",
  "Enrichi",
  "Entrées",
  "Entrées\nFoie gras maison — 18,50€\nServi avec confit d'oignon et toast brioché\n\nPlats\nMagret de canard — 24€\n…",
  "Entrées, Plats, Vins…",
  "envoi à",
  "Envoi en cours…",
  "Envoi…",
  "Envoie chaque type d'email à une adresse de ton choix pour vérifier que la config Resend + DNS marche après le setup du domaine custom.",
  "Envoie des SMS à tes clients",
  "Envois automatiques qui tournent tous seuls. Idéal pour les anniversaires et les relances d'avis Google.",
  "Envoyé",
  "Envoyer",
  "Envoyer le lien",
  "Envoyer tous les emails (6×)",
  "Envoyer un SMS",
  "envoyés",
  "Envoyés",
  "envoyés)",
  "Équipe",
  "Erreur lors de la sortie du mode SAV",
  "Erreur lors du démarrage du mode SAV",
  "Erreur réseau. Colle une URL à la place.",
  "Espace restaurateur",
  "est résilié immédiatement (sans pro-rata)",
  "Estimation sur la base du revenu mensuel × ancienneté des comptes. Pour le CA réel facturé, consulte Stripe Dashboard → Rapports → Revenu.",
  "et la base de participants",
  "et leurs cartes (catégories, produits, allergènes, suggestions)",
  "et notre",
  "Étape",
  "Évite trop tôt (avant 9h) et trop tard (après 20h).",
  "Évolution des scans",
  "Évolution temporelle. Survole le graphique pour voir les valeurs détaillées.",
  "Ex : « 100 unités », « Format A4 », « Pelliculage mat ». Affiché en liste sur la fiche produit.",
  "ex : 250",
  "Ex : bière (demi 3,50€ / pinte 6,50€) planche (petite 12€ / grande 24€) vin (verre 5€ / bouteille 28€).",
  "Ex : Demi Pinte Petite Grande",
  "Expédiée",
  "Expire",
  "Export CSV",
  "Exporter en CSV",
  "Fabriqué",
  "Facebook",
  "Facturation",
  "Facturation Admin",
  "Facture",
  "Facturé à",
  "Facture acquittée",
  "Factures abonnement",
  "factures et BC",
  "factures et bons de commande",
  "Factures Stripe",
  "Fermer",
  "Fichiers dans R2 (total)",
  "Filtre par statut, cherche un client, exporte en CSV.",
  "Filtrer",
  "Filtres",
  "Filtres avancés",
  "Filtres en cours…",
  "Fin",
  "Fine dining, sushi, hôtel",
  "Fonctionnalités",
  "Fond de la carte",
  "Format français accepté (06 / +33). Pour l'international, utilise le préfixe (+32 Belgique, +41 Suisse, +1 USA…).",
  "Format hexadécimal",
  "FR",
  "Frais de port",
  "Frais de port (Colissimo)",
  "Frais de port HT",
  "Frais de port mis à jour",
  "France",
  "France métropolitaine",
  "Freemium",
  "Funnel temps réel",
  "Fuseau horaire du restaurant",
  "Galerie",
  "Galerie (",
  "Garder programmée",
  "Génération…",
  "Génère et imprime un QR code par table, vitrine ou set de table. Un clic suffit pour démarrer.",
  "Génère ton premier QR code pour le coller sur tes tables, en vitrine, ou sur tes sets de table. Chaque scan sera tracké automatiquement.",
  "Générer mon premier QR code",
  "Générer un QR code",
  "générés et leurs statistiques de scan",
  "Gère les comptes restaurateurs, leurs plans et leurs statuts.",
  "Gère les produits que tes clients restaurateurs peuvent commander : sets de table, stickers, présentoirs, supports vitrine.",
  "Géré par Stripe. Résiliation et changement de plan à tout moment.",
  "Gère ta base clients (contacts collectés via la roulette ou ajoutés à la main), exploitable pour les campagnes SMS et automatisations.",
  "Gère ton profil, ton équipe, ta facturation et tes intégrations.",
  "Gérer l'équipe",
  "Gérer mon abonnement",
  "Gérer mon plan",
  "Glisse pour réordonner, masque ce que tu n'utilises pas.",
  "Glisse-dépose tes catégories, modifie tes plats, aperçu en direct à droite. Tes modifications sont sauvegardées toutes seules.",
  "Glisse, colle (Ctrl+V) ou clique pour uploader. Format carré recommandé, max 5 MB.",
  "Glisser, coller ou cliquer",
  "Grammage (g)",
  "Grille",
  "h00",
  "Happy Hour End",
  "Happy Hour Start",
  "happyHourEnd :",
  "happyHourStart :",
  "Hero layout",
  "Heure d'envoi",
  "Heure début",
  "Heure fin",
  "Historique de mes commandes",
  "Historique des envois",
  "Horaires de service",
  "Horaires personnalisés",
  "HT",
  "HT / mois",
  "HT TVA 20% incluse au paiement",
  "HTML",
  "IBAN :",
  "ID :",
  "Identité éditoriale",
  "ignorés",
  "Image",
  "Image d'illustration",
  "Image uploadée.",
  "Impayées",
  "Import CSV",
  "Import par photo",
  "Import…",
  "Importe ta carte par photo",
  "Importer ma carte",
  "Importer ma carte ici",
  "Importer ta carte depuis une photo",
  "Importer une photo",
  "Imprimé en France",
  "Imprimer",
  "Imprimer / PDF",
  "imprimés en France 🥖",
  "Inactifs",
  "Indicateurs Ruliz branchés sur la DB live.",
  "Influence le caractère visuel des titres sur la carte publique.",
  "Informations du compte",
  "Informations légales",
  "Infos",
  "Infos pratiques (synchronisées)",
  "Inscription restaurateur",
  "Inscriptions sur 30 jours",
  "Inscrit",
  "Insère 3 variants × 4 steps (J+0/J+3/J+7/J+14). Idempotent.",
  "Insights automatiques",
  "Instagram",
  "Intégrations tierces",
  "interested",
  "Invitation envoyée",
  "Invite tes collaborateurs à éditer la carte depuis l'onglet dédié.",
  "Inviter",
  "Inviter un membre",
  "IP",
  "IPs et user agents des connexions actuelles + récentes.",
  "irréversible",
  "Issus de la roulette d'avis",
  "j restant",
  "J+",
  "Jeu activé",
  "Jeu Participants",
  "Jeux",
  "Jeux roulette",
  "Jours d'affichage",
  "Jusqu'à (g)",
  "jusqu'à ce que tu mettes à jour ton moyen de paiement.",
  "L'IA ne suggère pas de réponse pour ce cas.",
  "L'image dépasse 5 MB.",
  "L'URL ne peut pas s'afficher dans une iframe (sécurité du site). Essayez une URL Ruliz ou désactivez X-Frame-Options côté serveur.",
  "L'utilisateur ne pourra plus se connecter. Ses restaurants restent visibles dans l'admin mais sortent du dashboard. Action réversible via Réactiver.",
  "La boutique est vide pour l'instant",
  "La langue dans laquelle tu écris ta carte. Anthropic traduit automatiquement vers les autres langues.",
  "La page Clients est incluse dans les offres supérieures",
  "La somme des probabilités doit faire",
  "La Table d'à côté",
  "Label du bouton",
  "Lance",
  "Lance les opérations one-shot depuis l'admin (zéro terminal nécessaire).",
  "Lance ou force une re-traduction",
  "Lancer (",
  "Lancer l'analyse",
  "langue",
  "Langue",
  "Langue de la carte",
  "Langue de saisie de la carte",
  "Langue du menu",
  "Langues consultées",
  "Le bistrot que vous auriez aimé tenir.",
  "Le bouton Spin redirige d'abord vers ton lien Google Review.",
  "Le client choisit son lot, on capte ses coordonnées en échange.",
  "Le compte aura accès à toutes les fonctionnalités sans paiement.",
  "Le fichier doit être un .csv",
  "Le jeu roulette est inclus dans le plan Pro",
  "Le jeu s'active uniquement entre ces deux dates. Laisse vide pour qu'il tourne en permanence tant qu'il est activé.",
  "Le lien de réinitialisation est incomplet ou a expiré. Refais une demande de nouveau mot de passe.",
  "Le membre doit déjà avoir un compte Ruliz. Il recevra un email de notification.",
  "Le membre perd l'accès à tes restaurants. Action réversible : tu peux le réinviter à tout moment.",
  "Le menu est inséré dans ta carte. Tu peux ensuite tout éditer dans l'éditeur classique.",
  "Le modal s'affiche tout seul quand un client scanne le QR code. 1 fois par session navigateur.",
  "Le mode sombre donne une carte chic style restaurant haut de gamme.",
  "Le mot de passe est envoyé par email le restaurateur peut le changer à la première connexion.",
  "Le nom et la description s'affichent en hero de ta carte publique.",
  "Le palier appliqué est le",
  "Le parcours complet d'un prospect — depuis l'import CSV jusqu'à la conversion en client Pro. Toutes les branches sont automatisées (incluant les réponses aux replies).",
  "Le PDF dépasse 8 MB.",
  "Le prospect clique preview → /signup?prospect=token → compte créé en 30s → email bienvenue",
  "Le site vitrine est inclus avec Pro (29,90 €) et Premium (44,90 €). Tu peux éditer le contenu, mais la sauvegarde est désactivée tant que tu n'upgrades pas.",
  "Le site vitrine est inclus dans les offres supérieures",
  "Le SMS «",
  "Le SMS marketing est inclus dans Premium",
  "Le SMS partira automatiquement à l'heure choisie (idéal pour les soirées, brunch dominical, etc.).",
  "Le Tire-Bouchon",
  "LeBistrot",
  "Les",
  "Les 6 actions les plus fréquentes pour un restaurateur.",
  "Les factures apparaîtront automatiquement dès ton premier paiement Pro ou Premium.",
  "les fiches clients, logs et facturation. À utiliser avec prudence.",
  "Les pop-ups événements sont inclus dans le plan Pro",
  "Les prospects avancent : queued → enriched → generated → sent → opened → clicked → converted.",
  "Libellé",
  "Libellé affiché au client",
  "Libellé visible",
  "Lien Google Review",
  "Lien invalide",
  "Light (recommandé)",
  "Limite atteinte pour ton plan actuel. Passe Premium pour des places illimitées.",
  "Limites (vide = illimité)",
  "Liste de tous les clients qui ont laissé leurs coordonnées via la roulette d'avis OU que tu as ajoutés manuellement. Utilisable pour les campagnes SMS et automatisations.",
  "Liste verticale",
  "Live",
  "Live feed",
  "Livraison",
  "Livraison 5 jours",
  "Livraison 5j",
  "Livrée",
  "Logo",
  "Logo carré (idéal 150×150px). Bannière en hero, ratio 16/9.",
  "Logo et bannière",
  "logos, bannières et photos",
  "Logs (",
  "Logs système",
  "Lot",
  "Lots et probabilités",
  "Lumineux, food-friendly",
  "lunchEnd :",
  "lunchStart :",
  "Magique",
  "MAIL_FROM :",
  "Manuels",
  "Marc",
  "Marge vs Brevo (×)",
  "Marier avec",
  "Marquer « Nouveau »",
  "Marquer perdu",
  "Masquée",
  "Masquée sur la carte publique",
  "Maximum",
  "Médias",
  "membre",
  "Membre retiré",
  "Membres",
  "Membres actuels",
  "Mentions légales & CGV",
  "Mentions légales, CGV et politique de confidentialité de Ruliz. Consulte-les à tout moment depuis ton espace.",
  "Mes commandes",
  "Mes commandes & factures",
  "Mes restaurants",
  "Message",
  "Message d'invitation",
  "Mets à jour ton moyen de paiement avant la prochaine échéance, sinon ton service sera suspendu automatiquement.",
  "Mettre à jour",
  "Midi + Soir",
  "Minimum 5 min dans le futur. Tu peux annuler depuis l'historique tant que l'envoi n'a pas commencé.",
  "Minimum 8 caractères. Ce sera ton nouveau mot de passe Ruliz.",
  "Mis à jour",
  "Mise à jour…",
  "Mise en avant carte — Vitrine",
  "Modalités de règlement",
  "Mode clair / sombre",
  "Mode d'affichage",
  "Mode démo admin",
  "Mode SAV terminé",
  "Modern (Geist sans-serif)",
  "Modifiable plus tard dans les paramètres.",
  "Modifications non enregistrées",
  "Moins",
  "Mon compte",
  "Mon panier",
  "Mon restaurant",
  "Montant",
  "Mot de passe",
  "Mot de passe initial",
  "Mot de passe mis à jour. Redirection…",
  "Mot de passe mis à jour. Tu peux te reconnecter.",
  "Mot de passe oublié ?",
  "Navigateurs",
  "Navigation",
  "Né(e)",
  "Nécessite une adresse renseignée dans l'onglet Infos. Désactivé par défaut.",
  "negative",
  "NEW",
  "Nom",
  "Nom A-Z",
  "Nom affiché",
  "Nom de famille",
  "Nom de l'expéditeur",
  "Nom de la campagne (interne, pour retrouver dans l'historique)",
  "Nom du destinataire",
  "Nom du jeu (interne)",
  "Nom du produit",
  "Nom du restaurant *",
  "Nombre de SMS",
  "Note (0-5)",
  "Note spéciale (optionnel)",
  "Notes (optionnel)",
  "Notes du client",
  "Notre carte",
  "Nouveau",
  "Nouveau client",
  "Nouveau mot de passe",
  "Nouveau pop-up",
  "Nouveau produit",
  "Nouveau restaurant",
  "Nouveaux",
  "Nouveaux 24h",
  "Nouveaux clients (bleu) et nouveaux restaurants (gris).",
  "Nouvelle automatisation",
  "Numéro",
  "offert :",
  "Offerts ✓",
  "Offre / Storytelling",
  "Offrir",
  "Offrir des jours de pro/premium",
  "OK",
  "Open",
  "Open rate",
  "Opt-out SMS",
  "optionnel",
  "Origine géographique",
  "Orphelins (tous âges)",
  "Orphelins > 30 jours (cleanup)",
  "ou",
  "Oublié ?",
  "Outreach Smartlead — 4 steps × 4 variants",
  "Ouvert",
  "Ouvertes",
  "Ouverture",
  "Ouvrir dans un nouvel onglet",
  "Ouvrir l'éditeur",
  "Override la catégorie. Utile pour un cocktail visible uniquement en happy hour dans une carte normalement 24/7.",
  "Override la couleur du thème global. Utile pour distinguer visuellement une catégorie (ex: rouge pour les épicés).",
  "Pack",
  "Pack Découverte",
  "Paiement",
  "Paiement annulé. Tu peux réessayer ci-dessus à tout moment.",
  "Paiement en retard.",
  "Paiement par carte bancaire en ligne via Stripe (lien sécurisé envoyé par email) ou par virement bancaire à réception de la commande, échéance",
  "Paiement reçu ! Tes SMS sont créditées.",
  "Paiement sécurisé",
  "Paliers tarifaires par poids",
  "Panier",
  "par Stripe (carte bancaire, SEPA, Apple Pay)",
  "par un partenaire local circuit court, emploi français",
  "Paragraphe",
  "Paragraphes (",
  "Paramètres",
  "Paramètres système",
  "participant",
  "Participant",
  "Participants",
  "Participations jeu",
  "Pas de données.",
  "Pas encore de clics. Dès que tes premiers clients exploreront ta carte, leurs interactions apparaîtront ici.",
  "Pas encore de compte ?",
  "Pas encore de produits dans ta carte. Va dans",
  "Pas encore de QR code",
  "Passer",
  "Passer en",
  "Payé",
  "Payée le",
  "Payées",
  "pays",
  "Pays",
  "Pays de ton restaurant",
  "PDF",
  "PDF importé",
  "PDF importé.",
  "Pelliculage mat pro",
  "Pense à vérifier ton dossier",
  "Perdus",
  "Période",
  "Période…",
  "Personnaliser",
  "Phase validation — démo",
  "Photo",
  "Photo / PDF",
  "Photo About à gauche",
  "Photo du chef, de la salle, d'un plat signature",
  "Photo du produit",
  "Pilotage de la campagne",
  "Pilotage du workflow",
  "Pipeline d'acquisition cold-email avec cartes pré-générées. Track temps réel des ouvertures, clics et conversions.",
  "Pipeline en temps réel",
  "Plan",
  "Plan & paiement",
  "Plan ↑ (Free → Premium)",
  "Plan ↓ (Premium → Free)",
  "Plan actuel",
  "Plan associé à",
  "Plan d'accès",
  "Plan freemium par défaut (modifiable dans « Droits & Plans »).",
  "Plan gratuit",
  "Plan Pro ou Premium requis",
  "Plans & fonctionnalités",
  "Plans des restaurants",
  "Plans mis à jour",
  "Plus",
  "Plus d'actions",
  "Plus de détails",
  "Plus joli à partager.",
  "Plus max",
  "Plus que",
  "Plus tu achètes en gros, moins c'est cher. Crédits non expirables, paiement sécurisé.",
  "Plusieurs tailles / volumes ?",
  "pnpm tsx scripts/seed-email-variants.ts",
  "poids total",
  "Poids unitaire du produit en grammes. Sert au calcul automatique des frais de port (paliers Colissimo configurés dans /admin/boutique). Mets 0 si le produit est dématérialisé.",
  "politique de confidentialité",
  "Politique de confidentialité",
  "Pop-up automatique à l'ouverture",
  "Pop-ups",
  "Populaire / Économie / ...",
  "Port",
  "Position",
  "Pouls temps réel : derniers signups, dernières commandes boutique, dernières participations roulette. Cap à 20 par flux.",
  "Pour chaque jour, active les services et saisis tes heures. Affiché sur ton mini-site vitrine et utilisé pour générer les créneaux Schema.org SEO.",
  "pour les générer.",
  "pour personnaliser. L'estimation du coût s'affiche en direct.",
  "pour pouvoir les sélectionner.",
  "Pour qu'on imprime ton QR code unique.",
  "Pour redescendre vers",
  "Pourquoi commander chez Ruliz ?",
  "Pré-traduire le panel",
  "Pré-traduire toutes les langues",
  "premier",
  "Premier contact",
  "Premium",
  "Prends en photo ton menu papier (ou uploade un PDF page). Claude Vision lit l'image et crée les catégories + produits + prix automatiquement. Tu peux ensuite éditer manuellement.",
  "Prends ta carte papier en photo le système détecte tout seul catégories, plats, prix et allergènes en",
  "Prends une photo nette de ton menu (ou colle une URL d'image / PDF). Cadre le texte bien droit, évite ombres et reflets. JPEG, PNG, WebP ou PDF. Max 8 MB.",
  "Prénom",
  "Presets :",
  "Prêt à être analysé",
  "Preview",
  "Preview →",
  "Preview du site",
  "Preview live",
  "price_…",
  "Prix",
  "Prix (",
  "Prix (€)",
  "Prix annuel HT (€)",
  "Prix des packs SMS",
  "Prix mensuel HT (€)",
  "Prix unitaire",
  "Prix, allergènes, photos, traduction automatique sur le téléphone de chaque client, en un scan.",
  "Pro",
  "Problèmes paiement",
  "produit",
  "Produit",
  "Produit en rupture de stock",
  "Produit supprimé",
  "produits",
  "Produits en vitrine",
  "Produits les plus consultés",
  "Profil",
  "Profil mis à jour",
  "Programmation (optionnel)",
  "Programmée",
  "Programmer l'envoi",
  "Progression",
  "promouvoir en admin donne accès à",
  "Propriétaire",
  "Propulsé par Ruliz",
  "prospects · page",
  "Prospects de la campagne",
  "Publié visible et commandable",
  "Publiés",
  "Purge toutes les images R2 du client (logos, photos…)",
  "QR code",
  "QR code de ton site",
  "QR code généré.",
  "QR code supprimé",
  "QR codes",
  "QR indisponible",
  "QR site",
  "Qté",
  "Quand tes clients consultent ta carte. Plus c'est foncé, plus il y a de scans.",
  "Quantité",
  "question",
  "Queued",
  "queued)",
  "Quitter",
  "Rafraîchir l'aperçu",
  "Rating",
  "Re-générer",
  "Re-tape ton email exact",
  "Re-traduction lancée. Les langues seront disponibles dans 1-2 min.",
  "Re-traduire",
  "Re-traduire le menu de ce restaurant",
  "Réactions prospect",
  "Réactiver",
  "Réactiver le compte",
  "Recharger",
  "Recharger la preview",
  "Recherche par nom, email, téléphone…",
  "Rechercher un emoji…",
  "Rechercher un produit…",
  "Rechercher une catégorie…",
  "Reçois tous les emails à cette adresse pour vérifier le rendu visuel + la délivrabilité. Vérifie aussi les spams si tu reçois rien.",
  "Recommandé",
  "Récupération de compte",
  "Récupère des avis Google gagne des étoiles",
  "Récupère les coordonnées de tes clients pendant qu'ils laissent un avis 5 étoiles. Tu remontes dans les recherches Google en quelques scans.",
  "Récupère les coordonnées de tes clients via la roulette, puis envoie-leur un SMS pour les faire revenir. Idéal pour remplir tes services creux.",
  "Récurrents",
  "Redirection...",
  "Réf. Stripe : …",
  "Référencés en DB",
  "Réglée par carte bancaire via Stripe le",
  "Régler maintenant",
  "Réinitialiser",
  "Réinitialiser (auto top-4)",
  "Relance le petit tour guidé qui t'explique comment mettre ta carte en ligne. Utile si tu as zappé la 1ère fois ou si tu veux le montrer à un collègue.",
  "Relance soft",
  "Remplacer",
  "Remplacer le menu existant",
  "Renouvellement",
  "Renouvellement le",
  "Renseigne",
  "Renseigne ton email pour recevoir un lien de réinitialisation (valable 1h).",
  "replies",
  "Replies",
  "Reply",
  "Reply auto humanisée (AI Marketer)",
  "Réponse reçue",
  "Réponse serveur invalide. Colle une URL à la place.",
  "Réponses prospects (AI-classifiées)",
  "Reprenons là où vous vous êtes arrêté",
  "Réseaux",
  "Réseaux sociaux & avis",
  "RESEND_API_KEY :",
  "Réserver",
  "Reset",
  "Reset mot de passe",
  "Reset password",
  "restant",
  "restaurant",
  "Restaurant",
  "Restaurant :",
  "Restaurant créé !",
  "Restaurant créé pour ce client.",
  "Restaurant mis à jour",
  "Restaurant supprimé.",
  "restaurants",
  "Restaurants",
  "Restaurants (",
  "restos",
  "Retape le mot de passe",
  "Retirer",
  "Retour",
  "Retour 14j",
  "Retour à l'admin",
  "Retour à la campagne",
  "Retour à la connexion →",
  "Retour à la roulette",
  "Réussi",
  "Revenir au mockup",
  "Revenu mensuel",
  "Revenu mensuel × 12",
  "Revenu mensuel récurrent",
  "Revenu mensuel récurrent, ARR, abonnements actifs, paiements en retard, CA généré.",
  "Revenus",
  "Reviens bientôt de nouveaux supports arrivent.",
  "Révoquer le cadeau",
  "Rien trouvé.",
  "Rôle",
  "Rôle de l'utilisateur",
  "Roulette 24h",
  "Roulette d'avis",
  "roulettes / jeux",
  "Ruliz",
  "Ruliz v1",
  "ruliz.fr/carte/le-tire-bouchon",
  "Rupture",
  "S'abonner",
  "S'affiche au chargement de la carte publique pendant la période active.",
  "sans passer par le form. Si ça marche ici mais pas dans /dashboard/restaurant, le problème est côté form/auto-save.",
  "Sauvegarde…",
  "Sauvegarder",
  "Sauvegarder maintenant",
  "Save → preview refresh + CDN purge (~120s).",
  "Save raw SQL OK",
  "Scanne pour consulter la carte",
  "scans",
  "Scans",
  "Scans / visiteur",
  "Scans 30j",
  "Scans ce mois",
  "Scans total",
  "Scans totaux",
  "scans/heure",
  "Scrape + OCR Anthropic",
  "Se connecter",
  "Se connecter →",
  "Se déconnecter",
  "Secondaire (réservé)",
  "Sections affichées",
  "Seed…",
  "Sélectionne tes destinataires (",
  "Séquence A/B/C/D pour chaque step. Drip 200/jour. Bandit Thompson Sampling.",
  "sera retiré de ta base. Ses participations à la roulette resteront en historique. Action irréversible.",
  "Service continu",
  "Services opérationnels",
  "Sessions récentes",
  "Set de table imprimé 100×",
  "Sets de table imprimés, stickers QR, présentoirs, supports vitrine. Ton QR code unique pré-imprimé, livré chez toi.",
  "Sets de table, stickers vitrine, présentoirs, chevalets… ton QR code pré-imprimé sur du matériel pro, livré chez toi en 5 jours.",
  "Sets de table, Stickers, Vitrine…",
  "Seuil livraison offerte (€)",
  "Si commande ≥ ce montant, frais de port = 0€.",
  "Si décoché, ce client ne recevra aucun SMS (RGPD).",
  "Si désactivé, livraison gratuite pour toutes les commandes.",
  "Si la fin est avant le début (ex: 22h → 02h), la catégorie passe minuit (service de nuit).",
  "Si ton solde n'a pas encore bougé, rafraîchis la page dans quelques secondes.",
  "si tu ne le vois pas tout de suite.",
  "Si un compte existe pour",
  "Si une période est déjà active, les jours s'ajoutent à la date de fin actuelle.",
  "Signature (optionnel)",
  "Signup activé",
  "SIRET",
  "SIRET :",
  "Site désactivé (404)",
  "Site en ligne",
  "Site sauvegardé. Preview rafraîchie.",
  "Site vitrine",
  "Site web",
  "Skip les produits déjà traduits (rapide).",
  "Skip les produits déjà traduits.",
  "Slug (URL)",
  "Slug (vide = utilise l'ID numérique)",
  "SMS",
  "SMS chacun",
  "SMS de plus. Achète un pack ci-dessous pour continuer.",
  "SMS maintenant",
  "SMS marketing",
  "SMS par destinataire car message long)",
  "SMS utilisés",
  "Soir uniquement",
  "Soirée vins du jeudi",
  "Soit",
  "Solde après envoi",
  "Solde insuffisant. Il te faut",
  "Sombre",
  "Somme des abonnements actifs sur 1 mois",
  "sont conservés en archives (obligation comptable 10 ans, art. L123-22 Code de commerce) mais toutes tes données personnelles sont anonymisées.",
  "Sous-catégorie",
  "Sous-total",
  "Sous-total articles",
  "Sous-total articles HT",
  "Spam",
  "Spécialité de la maison",
  "Split (50/50 image + texte)",
  "Status check des services externes. Si un service est ❌ rouge, ajoute la / les variable(s) d'env Railway puis redéploie.",
  "Status des intégrations, infos de build et configuration globale. Les valeurs sensibles passent par les env vars Railway cette page est read-only.",
  "Statut",
  "Statut mis à jour",
  "Statut resto",
  "Statut Stripe",
  "Step",
  "Stock",
  "Stock maximum",
  "Stripe Dashboard ↗",
  "Stripe n'a pas pu débiter ton moyen de paiement. Mets-le à jour avant la prochaine échéance, sinon ton service sera suspendu automatiquement.",
  "Stripe n'est pas encore configuré. Contacte le support.",
  "Stripe non configuré",
  "Stripe price ID (annuel)",
  "Stripe price ID (mensuel)",
  "STRIPE_*_PRICE_ID",
  "STRIPE_SECRET_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "Style",
  "Style de typographie",
  "Subs actives",
  "Suggestions d'accompagnement affichées à tes clients dans la modale produit (ex: un plat suggère un vin).",
  "Suis l'avancement de tes bons de commande boutique, télécharge tes factures et retrouve l'historique de tes achats SMS.",
  "Suis tes bons de commande boutique en direct + télécharge toutes tes factures (abonnement et achats de SMS).",
  "Suivant →",
  "Sujet",
  "Support FR",
  "Supprimé",
  "Supprime définitivement ton compte Ruliz, tes restaurants, tes QR codes, tes photos et toutes les données associées.",
  "Supprimer",
  "SUPPRIMER",
  "Supprimer «",
  "Supprimer ce client ?",
  "Supprimer ce produit ?",
  "Supprimer ce QR code ?",
  "Supprimer cette catégorie ?",
  "Supprimer définitivement",
  "Supprimer définitivement (RGPD)",
  "Supprimer définitivement ce compte ?",
  "Supprimer définitivement ton compte ?",
  "Supprimer mon compte",
  "sur",
  "Sur la carte publique, les sous-catégories apparaissent en JAUNE à l'intérieur de leur catégorie parente. Idéal pour structurer (ex: Vins ↳ Rouges / Blancs / Rosés).",
  "Suspendre",
  "Suspendre le compte",
  "Suspendu",
  "suspendus",
  "Système",
  "Systèmes",
  "Table 5, Vitrine…",
  "Tableau de bord",
  "Tagline (phrase d'accroche hero + footer)",
  "Tags :",
  "Taille / volume",
  "Tape ton message. Utilise",
  "Tape une caractéristique puis Entrée",
  "Tape une commande ou cherche…",
  "Tarif (€)",
  "Tarif & Stripe",
  "Tarif forfaitaire de secours (€)",
  "TB",
  "Tél :",
  "Tél :",
  "Télécharger",
  "Télécharger PDF",
  "Télécharger PNG",
  "Téléphone",
  "Téléphone (optionnel)",
  "Téléphone, email, adresse, code postal, ville, horaires d'ouverture, réseaux sociaux et Google Maps sont auto-pullés depuis",
  "Témoignages",
  "Témoignages (",
  "Terminer",
  "Tes",
  "Tes clients",
  "Tes clients laissent un avis 5 étoiles et tentent de gagner un lot. Tu remontes dans les recherches Google et tu récupères leurs contacts en même temps.",
  "Tes collaborateurs",
  "Tes QR codes",
  "Test emails",
  "Tester les emails transactionnels",
  "Texte",
  "Thème",
  "TikTok",
  "Tip",
  "Titre",
  "Titre de la note",
  "Titre de la section",
  "Titre du restaurant",
  "Titres de catégories",
  "Ton",
  "Ton abonnement n'a pas pu être prélevé. Ta carte publique est",
  "Ton logo + couleurs",
  "Ton mini-site web",
  "Ton panier est vide",
  "Ton QR code personnalisé",
  "Ton service sera arrêté à la fin de la période en cours. Réactive un plan pour continuer.",
  "Top 10 villes représentées",
  "Top 8 pays",
  "Top QR codes",
  "Total",
  "Total :",
  "Total acheté",
  "Total cumulé :",
  "Total envoyé",
  "Total HT",
  "Total participants",
  "Total sur la période :",
  "Toujours (suit la catégorie)",
  "Tous",
  "Tous les abonnements (",
  "Tous les bons de commande boutique, achats de packs SMS et factures d'abonnement de ce client. Tu peux changer le statut d'un BC directement depuis cette page : clic sur le statut → choisis le nouveau → enregistré instantanément.",
  "Tous les clients",
  "Tous les contacts",
  "Tous les jeux configurés par les restaurants de ce client.",
  "Tous les leads captés par ta roulette — tu peux les exporter pour les contacter par email ou SMS.",
  "Tous les produits qu'elle contient (",
  "Tous les scans déjà comptabilisés seront conservés mais ne pourront plus être attribués. Action irréversible.",
  "Tous les statuts",
  "Tous plans",
  "Tous statuts",
  "Tout effacer",
  "Tout est automatisé. Tu ne touches que le contenu (variants emails) et les paramètres campagne.",
  "Tout re-traduire (forcer)",
  "toutes",
  "Toutes les commandes",
  "Toutes les commandes boutique",
  "Toutes les replies reçues via Smartlead, classifiées automatiquement par Anthropic Haiku.",
  "Toutes tes commandes boutique avec leur statut de livraison.",
  "Tracking automatique via webhook Smartlead → /api/outreach/event",
  "Traduire les nouveautés",
  "Trafic carte publique",
  "Tri ascendant.",
  "Trier par",
  "Triés par date de création (plus récents en haut).",
  "Triés par nombre de clics depuis le lancement.",
  "Tu navigues dans le panel client avec ton restaurant fictif. Aucun client réel ne voit cet espace.",
  "Tu pars déjà ?",
  "Tu peux reprendre le tour quand tu veux depuis « Aide » en bas de la sidebar.",
  "Tu seras redirigé vers la page de paiement sécurisée Stripe. Facture PDF disponible après paiement.",
  "Tu te souviens de ton mot de passe ?",
  "Tu utilises le plan freemium. Pas d'échéance, pas de facturation.",
  "TVA",
  "TVA :",
  "TVA acquittée sur les encaissements Conserver cette facture pendant 10 ans (art. L123-22 Code de commerce).",
  "TVA non applicable, art. 293 B du CGI",
  "Typographie",
  "Un mini-site web éditorial généré depuis ta carte (infos pratiques, branding, plats). Disponible selon ton plan.",
  "Un site éditorial moderne, généré depuis ta carte. Les infos pratiques, ton branding et tes plats sont auto-pullés. Tu n'as qu'à personnaliser le contenu éditorial (à propos, témoignages, galerie).",
  "Une carte qui parle 14 langues.",
  "Une cuisine. Trois mouvements.",
  "Une phrase courte sous le titre. Italique automatique.",
  "unité",
  "unités",
  "unsubscribe",
  "Upload CSV",
  "URL :",
  "URL de réservation (TheFork, Zenchef…)",
  "URL de votre carte publique Ruliz",
  "URL du bouton",
  "URL enregistrée.",
  "URL personnalisée",
  "URL publique :",
  "Utilisé par le jeu roulette pour rediriger les clients qui veulent gagner un lot.",
  "utilisé uniquement si aucun palier défini",
  "Valable à vie",
  "Validation email",
  "Variant",
  "variants",
  "Variants",
  "Variants emails",
  "Variants emails — performance",
  "Vérifie tes articles et finalise ta commande.",
  "via",
  "vide = défaut",
  "Vide = illimité",
  "Vide = toute la journée",
  "Vignettes",
  "Ville",
  "Ville (optionnel)",
  "Visible sur la carte publique",
  "Visible sur la carte publique uniquement.",
  "Visite la boutique pour ajouter des articles.",
  "Visite la boutique pour découvrir nos supports physiques.",
  "Visiteur (lecture seule)",
  "Visiteurs / mois",
  "Visiteurs / semaine",
  "Visiteurs du jour",
  "Visiteurs uniques",
  "Visualisez et copiez les HTMLs vers Smartlead.ai. Variables Smartlead :",
  "Voir en ligne",
  "Voir la boutique",
  "Voir la carte",
  "Voir la carte publique",
  "Voir la photo",
  "Voir les commandes",
  "Voir les packs",
  "Voir les replies AI-classifiées",
  "Voir les statistiques",
  "Voir ma carte",
  "Voir ma carte publique",
  "Voir mes BC / factures",
  "Voir mon site",
  "Voir tous les participants",
  "Voir tous les QR codes",
  "Vos cartes, vos QR codes et vos statistiques sont restés en ordre.",
  "Votre carte digitale est prête. Créez votre compte en 30 secondes pour l'activer.",
  "vs 30 jours précédents",
  "Vue centralisée : tous les bons de commande boutique en cours (par défaut) et toutes les factures Stripe d'abonnement clients.",
  "Vue d'ensemble",
  "Vue financière",
  "Vue globale, tous clients confondus.",
  "Vues uniques",
  "Workers Inngest scrapent + génèrent cartes (~$0.01/prospect).",
  "Workflow",
  "Workflow campagne",
  "X » avec le détail au clic.",
  "Zone dangereuse",
];
